// TODO remove this and use the model generated by genome nexus API client
export interface ISignalSearch {
    queryType: string;
    hugoSymbol: string;
    // entrezGeneId: number;
    alteration: string;
    region: string;
    variant: string;
    description: string;
}
